name: Update News

on:
  schedule:
    - cron: '0 * * * *' # каждый час
  workflow_dispatch: # позволяет запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm install axios@0.27.2 cheerio@1.0.0-rc.12 --save-exact
      - name: Fetch and parse news
        run: node fetch_news.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add news.json
          git commit -m "Update news.json" || echo "No changes to commit"
          git push